name: Deploy Spinnaker

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64 

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create ubuntu user
      run: |
        sudo groupadd ubuntu
        sudo useradd -g ubuntu -s /bin/bash -d /home/ubuntu ubuntu
        sudo mkdir -p /home/ubuntu
        sudo chown -R ubuntu:ubuntu /home/ubuntu
        sudo sh -c 'echo "ubuntu	ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers'

    - name: Get Kube Config
      run: |
        aws eks update-kubeconfig --name eks-spinnaker --region us-east-1 --alias eks-spinnaker
    
    - name: Install Hallyard
      run: |
        curl -O https://raw.githubusercontent.com/spinnaker/halyard/master/install/debian/InstallHalyard.sh
        sudo bash InstallHalyard.sh --user runer && echo "success" || echo "failure"

    - name: Move Halyard config to default area
      run: |
        mkdir .hal
        ls -al
        mv halconfig ~/.hal/config

    - name: Deploy Spinnaker
      run: |
        hal deploy apply --no-validate


