name: Deploy Spinnaker

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64 

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create ubuntu user
      run: |
        sudo groupadd ubuntu
        sudo useradd -g ubuntu -s /bin/bash -d /home/ubuntu ubuntu
        sudo mkdir -p /home/ubuntu
        sudo chown -R ubuntu:ubuntu /home/ubuntu
        sudo sh -c 'echo "ubuntu	ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers'

    - name: Install kubectl
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

        # Verify the installation of kubectl
        kubectl help

        # Download and install aws-iam-authenticator
        curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
        chmod +x ./aws-iam-authenticator
        mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$HOME/bin:$PATH 
        echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc

        #Verify the installation of aws-iam-authenticator
        aws-iam-authenticator help            

    - name: Get Kube Config
      run: |
        aws eks update-kubeconfig --name eks-spinnaker --region us-east-1 --alias eks-spinnaker
    
    - name: Install Hallyard
      run: |
        curl -O https://raw.githubusercontent.com/spinnaker/halyard/master/install/debian/InstallHalyard.sh
        sudo bash InstallHalyard.sh --user runner && echo "success" || echo "failure"
        hal -v
        sudo update-halyard && echo "success" || echo "failure"
        

    - name: Move Halyard config to default area
      run: |
        mkdir .hal
        mv halconfig .hal/config

    - name: Set Persistent Storage
      run: |
        hal config storage s3 edit --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --no-validate

    - name: Set Version
      run: |
        export VERSION=1.24.4
        hal config version edit --version $VERSION
    
    - name: Deploy Spinnaker
      run: |
        cat .hal/config
        hal deploy apply --no-validate


